baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title='dfdfdfd'
theme = 'ananke'
site_name = 'Cyanfang Official Website | Xuzhou Cyanfang E-commerce Co., Ltd.'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
