baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = 'Cyanfang Official Website | Xuzhou Cyanfang E-commerce Co., Ltd.'
theme = 'ananke'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
